package omq.common.model;

import omq.common.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	
	public static final int REPORT_BLOCK_NUM = 3;
	
}
