package omq.common.model;

import omq.common.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	
	public static final int TYPE_NORMAL = 0;
    public static final int TYPE_SYSTEM = 1;  
	
}
