package omq.common.model;

import omq.common.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	
	public static final int REPORT_BLOCK_NUM = 3;
	
}
