package omq.common.model;

import omq.common.model.base.BaseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Share extends BaseShare<Share> {
	
	public static final int REPORT_BLOCK_NUM = 3;
	
}
